version: 2

project_name: forge

before:
  hooks:
    - go mod verify
    - go vet ./...

builds:
  - id: forge
    main: .
    binary: forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/RiseofRice/Forge/cmd.Version={{.Version}}

archives:
  - id: forge
    name_template: "forge_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: RiseofRice
    name: Forge
  draft: false
  prerelease: auto
  name_template: "ForgeCLI {{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
